name: Compile Wasm

on:
  push:
    branches:
      - master

jobs:
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: go version
      - run: make test
      - run: yarn --cwd ./browser-test && make browser-test
      - run: make build
      - run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'bot'
          rm .gitignore
          if git diff --stat | grep dist/ --quiet; then
            echo "There were changes. Committing.";
            git add app/dist/*;
            git commit -m "[GitHub action] Wasm module";
            git push
          else
            echo "No changes to commit. Skipping.";
          fi
